/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from "react";
import ForgeReconciler, {
  Text,
  Heading,
  CodeBlock,
  List,
  ListItem,
  Stack,
  Button,
  Inline,
  useProductContext,
} from "@forge/react";
import { requestJira, invoke } from "@forge/bridge";

/**
 * Key used to store and retrieve agent requirement review data in Jira Issue Properties.
 * Jira Issue Properties allow apps to persist key-value JSON data directly against a Jira issue.
 */
const PROPERTY_KEY = "antigravity_review";

/**
 * Converts standard Markdown formatted strings into Jira Wiki Markup format.
 * Jira's legacy issue comment REST API expects Jira Wiki Markup (e.g. h3. for headers,
 * *text* for bold, {code} for code blocks) to render rich formatted comments natively.
 *
 * @param {string} md - Raw markdown text generated by the agent
 * @returns {string} Converted Jira Wiki Markup text
 */
const markdownToJiraWiki = (md) => {
  if (!md) return "";
  let wiki = md;
  // Convert fenced code blocks ```lang ... ``` to Jira {code:lang} ... {code}
  wiki = wiki.replace(
    /```(\w+)?\n([\s\S]*?)```/g,
    (m, lang, code) =>
      `{code${lang ? ":" + lang : ""}}\n${code.trim()}\n{code}`,
  );
  // Convert markdown headings (# to ####) to Jira Wiki headings (h1. to h4.)
  wiki = wiki.replace(/^#### (.*$)/gim, "h4. $1");
  wiki = wiki.replace(/^### (.*$)/gim, "h3. $1");
  wiki = wiki.replace(/^## (.*$)/gim, "h2. $1");
  wiki = wiki.replace(/^# (.*$)/gim, "h1. $1");
  // Convert markdown bold **text** to Jira bold *text*
  wiki = wiki.replace(/\*\*(.*?)\*\*/g, "*$1*");
  // Convert inline backtick code `code` to Jira monospace {{code}}
  wiki = wiki.replace(/`([^`]+)`/g, "{{$1}}");
  return wiki;
};

/**
 * Dynamically parses raw markdown text and transforms it into native `@forge/react` UI Kit components.
 * Atlassian Forge UI Kit requires using official Atlassian components (<Text>, <Heading>, <CodeBlock>, <List>)
 * rather than standard HTML elements (<div>, <h1>, <pre>), ensuring a consistent Atlassian look and feel.
 *
 * @param {string} text - Content text to render
 * @returns {JSX.Element|null} Stack component containing rendered Atlassian UI Kit elements
 */
const renderMarkdown = (text) => {
  if (!text) return null;

  const lines = text.split("\n");
  const elements = [];
  let inCodeBlock = false;
  let codeBuffer = [];
  let currentList = [];

  /**
   * Helper function to flush buffered bullet points into an Atlassian UI Kit <List> component.
   */
  const flushList = () => {
    if (currentList.length > 0) {
      elements.push(
        <List key={`list-${elements.length}`}>
          {currentList.map((item, idx) => (
            <ListItem key={idx}>
              <Text>{item}</Text>
            </ListItem>
          ))}
        </List>,
      );
      currentList = [];
    }
  };

  lines.forEach((line, index) => {
    const trimmed = line.trim();

    // Toggle fenced code block state
    if (trimmed.startsWith("```")) {
      if (inCodeBlock) {
        elements.push(
          <CodeBlock key={`code-${index}`} text={codeBuffer.join("\n")} />,
        );
        codeBuffer = [];
        inCodeBlock = false;
      } else {
        flushList();
        inCodeBlock = true;
      }
      return;
    }

    // Buffer lines inside code blocks
    if (inCodeBlock) {
      codeBuffer.push(line);
      return;
    }

    // Strip inline formatting markdown symbols for clean text display
    const cleanText = trimmed.replace(/\*\*/g, "");

    // Map headings to @forge/react Heading components
    if (trimmed.startsWith("#### ")) {
      flushList();
      elements.push(
        <Heading key={index} as="h4">
          {cleanText.replace("#### ", "")}
        </Heading>,
      );
      return;
    }
    if (trimmed.startsWith("### ")) {
      flushList();
      elements.push(
        <Heading key={index} as="h3">
          {cleanText.replace("### ", "")}
        </Heading>,
      );
      return;
    }
    if (trimmed.startsWith("## ")) {
      flushList();
      elements.push(
        <Heading key={index} as="h2">
          {cleanText.replace("## ", "")}
        </Heading>,
      );
      return;
    }
    if (trimmed.startsWith("# ")) {
      flushList();
      elements.push(
        <Heading key={index} as="h1">
          {cleanText.replace("# ", "")}
        </Heading>,
      );
      return;
    }

    // Collect list items
    if (trimmed.startsWith("* ") || trimmed.startsWith("- ")) {
      currentList.push(cleanText.replace(/^[*|-]\s+/, ""));
      return;
    } else {
      flushList();
    }

    // Skip horizontal rules and empty lines
    if (!cleanText || cleanText === "---") {
      return;
    }

    // Default paragraph text element
    elements.push(<Text key={index}>{cleanText}</Text>);
  });

  flushList();
  return <Stack space="space.100">{elements}</Stack>;
};

/**
 * Main Antigravity Agent UI Kit Component.
 * Placed within Jira Issue View panels to provide real-time story requirement reviews.
 */
const App = () => {
  // Access Atlassian product context (contains information about current issue, user, site)
  const context = useProductContext();
  const [description, setDescription] = React.useState(
    "Initializing agent review...",
  );
  const [isLoading, setIsLoading] = React.useState(false);
  const [hasCompleted, setHasCompleted] = React.useState(false);

  // Extract current Jira Issue ID or Key from extension context
  const issueId =
    context?.extension?.issue?.id ||
    context?.extension?.issue?.key ||
    context?.extension?.issueId ||
    context?.extension?.issueKey;

  /**
   * Primary workflow handler for requirement reviews:
   * 1. Fetches issue details (description) via requestJira REST API.
   * 2. Checks Jira Issue Property (`antigravity_review`) to verify if a review already exists for this exact description.
   * 3. If cached review matches current description (and forced is false), loads review instantly from storage.
   * 4. If description changed or forced is true, calls backend resolver `startReviewStory` to start Agent Platform Agent interaction.
   * 5. Periodically polls `checkReviewStatus` backend resolver to render progress thoughts.
   * 6. Saves finished review and description to Jira Issue Property and posts native Jira issue comment.
   *
   * @param {boolean} forced - If true, bypasses cache and forces a fresh agent review invocation
   */
  const runAgentReview = async (forced = false) => {
    if (!issueId) {
      setDescription("No issue context available.");
      return;
    }

    setIsLoading(true);

    try {
      // Step 1: Fetch current issue details (including description) from Jira REST API
      setDescription("Fetching issue details...");
      const res = await requestJira(`/rest/api/2/issue/${issueId}`);
      if (!res.ok) {
        setDescription(`Failed to fetch issue details (Status: ${res.status})`);
        setIsLoading(false);
        return;
      }
      const data = await res.json();

      const rawDescription = data.fields?.description;
      const issueDescription =
        typeof rawDescription === "string"
          ? rawDescription
          : rawDescription
            ? JSON.stringify(rawDescription)
            : "No description provided";

      // Step 2: Check if a cached review exists in Jira Issue Property AND description has not changed
      if (!forced) {
        try {
          const propRes = await requestJira(
            `/rest/api/2/issue/${issueId}/properties/${PROPERTY_KEY}`,
          );
          if (propRes.ok) {
            const propJson = await propRes.json();
            // Validate that stored description matches current issue description
            if (
              propJson.value?.review &&
              propJson.value?.description === issueDescription
            ) {
              setDescription(propJson.value.review);
              setHasCompleted(true);
              setIsLoading(false);
              return;
            }
          }
        } catch (e) {
          console.log("Property check error:", e);
        }
      }

      // Step 3: Story description changed or forced re-run -> Invoke backend resolver to start agent review
      setDescription("Starting agent review for updated requirements...");
      const startRes = await invoke("startReviewStory", {
        description: issueDescription,
      });

      if (startRes.error) {
        setDescription(startRes.error);
        setIsLoading(false);
        return;
      }

      const interactionId = startRes.interactionId;
      setDescription("Agent is reviewing story requirements... Please wait.");

      // Step 4: Poll status from backend resolver every 4 seconds (up to 2 minutes total)
      const maxAttempts = 30;
      for (let attempt = 0; attempt < maxAttempts; attempt++) {
        await new Promise((r) => setTimeout(r, 4000));

        const statusRes = await invoke("checkReviewStatus", { interactionId });
        if (statusRes.error) {
          setDescription(statusRes.error);
          setIsLoading(false);
          return;
        }

        // When interaction completes, process final output
        if (statusRes.status === "completed") {
          const reviewText = statusRes.text;

          // Save review content AND current description to Jira Issue Property
          await requestJira(
            `/rest/api/2/issue/${issueId}/properties/${PROPERTY_KEY}`,
            {
              method: "PUT",
              headers: {
                Accept: "application/json",
                "Content-Type": "application/json",
              },
              body: JSON.stringify({
                review: reviewText,
                description: issueDescription,
                updatedAt: new Date().toISOString(),
              }),
            },
          );

          // Convert raw Markdown review to native Jira Wiki Markup format
          const wikiMarkupBody = markdownToJiraWiki(reviewText);

          // Add review as a native rich Jira issue comment
          await requestJira(`/rest/api/2/issue/${issueId}/comment`, {
            method: "POST",
            headers: {
              Accept: "application/json",
              "Content-Type": "application/json",
            },
            body: JSON.stringify({ body: wikiMarkupBody }),
          });

          setDescription(reviewText);
          setHasCompleted(true);
          setIsLoading(false);
          return;
        }

        // Render current progress step message
        const currentMessage =
          statusRes.latestMessage ||
          `Agent review in progress (step ${attempt + 1})...`;
        setDescription(currentMessage);
      }

      setDescription(
        "Agent review took longer than expected. Check Jira issue comments in a few moments.",
      );
    } catch (err) {
      console.error("Error processing story review:", err);
      setDescription(`Error: ${err.message || err}`);
    } finally {
      setIsLoading(false);
    }
  };

  // Trigger review flow on component mount once context and issueId are ready
  React.useEffect(() => {
    if (context && issueId) {
      runAgentReview(false);
    }
  }, [context, issueId]);

  return (
    <Stack space="space.200">
      {renderMarkdown(description)}
      {hasCompleted && !isLoading && (
        <Inline alignInline="end">
          <Button appearance="subtle" onClick={() => runAgentReview(true)}>
            Re-run Agent Review
          </Button>
        </Inline>
      )}
    </Stack>
  );
};

// Render the UI Kit root app into the Atlassian Forge container
ForgeReconciler.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
